#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 22, 2017 11:40:11 AM


import sys
import weather
import os
from dataIO import fileIO
import time
import datetime
import asyncio
import manage_item
import delete_item
import manage_settings
import traveltime

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def milk_remove_button(p1):
    w.Scrolledlistbox1.delete(0, END)
    result = ""
    i = 1
    to_remove = []
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        if the_list['Name'] == 'Milk':
            to_remove.append(the_list)
    for the_list in to_remove:
        lists = fileIO("data/list.json", "load")
        lists.remove(the_list)  
    fileIO("data/list.json", "save", lists)
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        result = "{}. Name: {}".format(i, the_list['Name'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        result = "Expiring on {}, {} {} {}".format(the_list['Day'], the_list['Date'], the_list['Month'], the_list['Year'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        i = i + 1

def weather_button(p1):
    w.information_box.configure(text=weather.get_weather())

def set_text(text):
    w.information_box.configure(text=text)

def togglesmallscreen():
    global top_level
    top_level.wm_state("iconic")

def togglebigscreen():
    global top_level
    top_level.wm_state("normal")

def refresh():
    w.Scrolledlistbox1.delete(0, END)
    result = ""
    i = 1
    c = -1
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        result = "{}. {}".format(i, the_list['Name'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        c = c + 1
        # result = "Expiring on {}".format(datetime.date(int(the_list['Year']), int(the_list['Month']), int(the_list['Date'])).strftime("%A, %d %B %Y"))
        # w.Scrolledlistbox1.insert(END, result + "\n")
        # c = c + 1
        dayleft = int(the_list['Date']) - datetime.date.today().day
        if datetime.date.today() == datetime.date(int(the_list['Year']), int(the_list['Month']), int(the_list['Date'])):
            result = "Expired ({})".format(datetime.date(int(the_list['Year']), int(the_list['Month']), int(the_list['Date'])).strftime("%A, %d %B %Y"))
            w.Scrolledlistbox1.insert(END, result + "\n")
            c = c + 1
            w.Scrolledlistbox1.itemconfig(c - 1, {'bg':'red'})
            w.Scrolledlistbox1.itemconfig(c, {'bg':'red'})
        elif (dayleft < 4) and (int(the_list['Month']) == datetime.date.today().month) and (int(the_list['Year']) == datetime.date.today().year):
            result = "Expiring on {}".format(datetime.date(int(the_list['Year']), int(the_list['Month']), int(the_list['Date'])).strftime("%A, %d %B %Y"))
            w.Scrolledlistbox1.insert(END, result + "\n")
            c = c + 1
            w.Scrolledlistbox1.itemconfig(c - 1, {'bg':'orange'})
            w.Scrolledlistbox1.itemconfig(c, {'bg':'orange'})
        else:
            result = "Expiring on {}".format(datetime.date(int(the_list['Year']), int(the_list['Month']), int(the_list['Date'])).strftime("%A, %d %B %Y"))
            w.Scrolledlistbox1.insert(END, result + "\n")
            c = c + 1
        i = i + 1
    root.after(1000, refresh)

def main():
    refresh()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    check_folders()
    check_files()
    main()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def manage():
    manage_item.create_FridgeBud(root)

def remove_item():
    delete_item.create_FridgeBud(root)

def settings():
    manage_settings.create_FridgeBud(root)

def get_traffic():
    value = traveltime.get_travel_time()
    w.traffic_label.configure(text=value)

def show_traffic_location_1(p1):
    value = traveltime.get_travel_time()
    w.traffic_label.configure(text=value)

def show_traffic_location_2(p1):
    value = traveltime.get_travel_time2()
    w.traffic_label.configure(text=value)

def check_folders():
    if not os.path.exists("data/"):
        print("Creating data/ folder...")
        os.makedirs("data/")


def check_files():
    f = "data/list.json"
    if not fileIO(f, "check"):
        print("Creating empty list.json...")
        fileIO(f, "save", [])
    f = "data/settings.json"
    if not fileIO(f, "check"):
        print("Creating empty settings.json...")
        fileIO(f, "save", [{"Country": "Singapore", "Home": "648324 Singapore", "Location 1": "648324 Singapore", "Location 2": "139651 Singapore"}])

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()