#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 10, 2017 06:40:56 PM


import sys
import subprocess

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def manage_item_support(p1):
    value = w.Entry1.get()
    import manage_item_support
    manage_item_support.returnname(value)
    destroy_window()

def country(p1):
    value = w.Entry1.get()
    import manage_settings_support
    manage_settings_support.country(value)
    destroy_window() 

def home(p1):
    value = w.Entry1.get()
    import manage_settings_support
    manage_settings_support.home(value)
    destroy_window() 

def location1(p1):
    value = w.Entry1.get()
    import manage_settings_support
    manage_settings_support.location1(value)
    destroy_window() 

def location2(p1):
    value = w.Entry1.get()
    import manage_settings_support
    manage_settings_support.location2(value)
    destroy_window() 

def country_cancel(p1):
    import manage_settings_support
    manage_settings_support.country_cancel()
    destroy_window() 

def home_cancel(p1):
    import manage_settings_support
    manage_settings_support.home_cancel()
    destroy_window() 

def location1_cancel(p1):
    import manage_settings_support
    manage_settings_support.location1_cancel()
    destroy_window() 

def location2_cancel(p1):
    import manage_settings_support
    manage_settings_support.location2_cancel()
    destroy_window() 

def toggleKeyboard():
    p = subprocess.Popen(['florence show'], shell=True, stdout= subprocess.PIPE, stderr= subprocess.PIPE, universal_newlines=True)
    if not "" == p.stderr.readline():
        subprocess.Popen(['florence'], shell=True)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import popup
    popup.vp_start_gui()

