#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 22, 2017 11:40:11 AM


import sys
import weather
import os
from dataIO import fileIO
import time
import datetime
import asyncio

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def milk_add_button(p1):
    w.Scrolledlistbox1.delete(0, END)
    result = ""
    i = 1
    lists = fileIO("data/list.json", "load")
    date = int(time.time() + 86400)
    lists.append({"Name": "Milk", "Timeleft": date})
    fileIO("data/list.json", "save", lists)
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        timeleft = the_list["Timeleft"] - int(time.time())
        result = "{}. Name: {}".format(i, the_list['Name'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        result = "Expired On: {}".format(datetime.timedelta(seconds=timeleft))
        w.Scrolledlistbox1.insert(END, result + "\n")
        i = i + 1

def milk_remove_button(p1):
    w.Scrolledlistbox1.delete(0, END)
    result = ""
    i = 1
    to_remove = []
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        if the_list['Name'] == 'Milk':
            to_remove.append(the_list)
    for the_list in to_remove:
        lists = fileIO("data/list.json", "load")
        lists.remove(the_list)  
    fileIO("data/list.json", "save", lists)
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        timeleft = the_list["Timeleft"] - int(time.time())
        result = "{}. Name: {}".format(i, the_list['Name'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        result = "Expired On: {}".format(datetime.timedelta(seconds=timeleft))
        w.Scrolledlistbox1.insert(END, result + "\n")
        i = i + 1

def weather_button(p1):
    w.information_box.configure(text=weather.get_weather())

def refresh():
    w.Scrolledlistbox1.delete(0, END)
    result = ""
    i = 1
    lists = fileIO("data/list.json", "load")
    for the_list in lists:
        timeleft = the_list["Timeleft"] - int(time.time())
        result = "{}. Name: {}".format(i, the_list['Name'])
        w.Scrolledlistbox1.insert(END, result + "\n")
        result = "Expired On: {}".format(datetime.timedelta(seconds=timeleft))
        w.Scrolledlistbox1.insert(END, result + "\n")
        i = i + 1
    root.after(1000, refresh)

def main():
    refresh()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    main()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def check_folders():
    if not os.path.exists("data/"):
        print("Creating data/ folder...")
        os.makedirs("data/")


def check_files():
    f = "data/list.json"
    if not fileIO(f, "check"):
        print("Creating empty list.json...")
        fileIO(f, "save", [])


check_folders()
check_files()

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()
    print("START 1")
    GUI.main()
    print("START 2")