#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 30, 2017 11:16:11 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global other_item_text
    other_item_text = StringVar()

def add_other_button(p1):
    print('manage_item_support.add_other_button')
    sys.stdout.flush()

def day_minus_button(p1):
    print('manage_item_support.day_minus_button')
    sys.stdout.flush()

def day_plus_button(p1):
    print('manage_item_support.day_plus_button')
    sys.stdout.flush()

def drinks_button(p1):
    print('manage_item_support.drinks_button')
    sys.stdout.flush()

def fish_button(p1):
    print('manage_item_support.fish_button')
    sys.stdout.flush()

def fruits_button(p1):
    print('manage_item_support.fruits_button')
    sys.stdout.flush()

def home_button(p1):
    print('manage_item_support.home_button')
    sys.stdout.flush()

def meat_button(p1):
    print('manage_item_support.meat_button')
    sys.stdout.flush()

def milk_button(p1):
    print('manage_item_support.milk_button')
    sys.stdout.flush()

def vegetables_button(p1):
    print('manage_item_support.vegetables_button')
    sys.stdout.flush()

def xxx(p1):
    print('manage_item_support.xxx')
    sys.stdout.flush()

def year_minus_button(p1):
    print('manage_item_support.year_minus_button')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import manage_item
    manage_item.vp_start_gui()

