#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m40" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1024x600+343+145
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1680 1005
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "FridgeBud"
    vTcl:DefineAlias "$top" "delete_item" vTcl:Toplevel:WidgetProc "" 1
    listbox $top.lis38 \
        -background white -font TkFixedFont -foreground {#000000} -height 506 \
        -width 362 
    .top37.lis38 configure -font TkFixedFont
    .top37.lis38 insert end text
    vTcl:DefineAlias "$top.lis38" "item_list" vTcl:WidgetProc "delete_item" 1
    label $top.lab39 \
        -background {#d9d9d9} -foreground {#000000} -text {Item list} 
    vTcl:DefineAlias "$top.lab39" "item_list_box" vTcl:WidgetProc "delete_item" 1
    menu $top.m40 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    entry $top.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent41" "item_number_box" vTcl:WidgetProc "delete_item" 1
    button $top.but42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 1 
    vTcl:DefineAlias "$top.but42" "Num1" vTcl:WidgetProc "delete_item" 1
    button $top.cpd43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 2 
    vTcl:DefineAlias "$top.cpd43" "Num2" vTcl:WidgetProc "delete_item" 1
    button $top.cpd44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 3 
    vTcl:DefineAlias "$top.cpd44" "Num3" vTcl:WidgetProc "delete_item" 1
    button $top.cpd45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 4 
    vTcl:DefineAlias "$top.cpd45" "Num4" vTcl:WidgetProc "delete_item" 1
    button $top.cpd46 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 5 
    vTcl:DefineAlias "$top.cpd46" "Num5" vTcl:WidgetProc "delete_item" 1
    button $top.cpd47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 6 
    vTcl:DefineAlias "$top.cpd47" "Num6" vTcl:WidgetProc "delete_item" 1
    button $top.cpd48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 7 
    vTcl:DefineAlias "$top.cpd48" "Num7" vTcl:WidgetProc "delete_item" 1
    button $top.cpd49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 8 
    vTcl:DefineAlias "$top.cpd49" "Num8" vTcl:WidgetProc "delete_item" 1
    button $top.cpd50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 9 
    vTcl:DefineAlias "$top.cpd50" "Num9" vTcl:WidgetProc "delete_item" 1
    button $top.cpd51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 
    vTcl:DefineAlias "$top.cpd51" "Num0" vTcl:WidgetProc "delete_item" 1
    button $top.cpd52 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Clear 
    vTcl:DefineAlias "$top.cpd52" "clear_button" vTcl:WidgetProc "delete_item" 1
    button $top.cpd53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Enter 
    vTcl:DefineAlias "$top.cpd53" "enter_button" vTcl:WidgetProc "delete_item" 1
    button $top.cpd55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Home 
    vTcl:DefineAlias "$top.cpd55" "home_button" vTcl:WidgetProc "delete_item" 1
    label $top.lab56 \
        -background {#d9d9d9} -foreground {#000000} -text Label 
    vTcl:DefineAlias "$top.lab56" "item_status_box" vTcl:WidgetProc "delete_item" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis38 \
        -in $top -x 30 -y 60 -width 362 -relwidth 0 -height 506 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 180 -y 20 -width 61 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent41 \
        -in $top -x 697 -y 130 -width 272 -relwidth 0 -height 47 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but42 \
        -in $top -x 690 -y 190 -width 87 -relwidth 0 -height 62 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd43 \
        -in $top -x 790 -y 190 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd44 \
        -in $top -x 890 -y 190 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd45 \
        -in $top -x 690 -y 260 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd46 \
        -in $top -x 790 -y 260 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd47 \
        -in $top -x 890 -y 260 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd48 \
        -in $top -x 690 -y 330 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd49 \
        -in $top -x 790 -y 330 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd50 \
        -in $top -x 890 -y 330 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd51 \
        -in $top -x 790 -y 400 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd52 \
        -in $top -x 690 -y 400 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd53 \
        -in $top -x 890 -y 400 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.cpd55 \
        -in $top -x 890 -y 490 -width 87 -height 62 -anchor nw \
        -bordermode inside 
    place $top.lab56 \
        -in $top -x 420 -y 70 -width 241 -relwidth 0 -height 484 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

