#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 18, 2017 03:52:38 PM


import sys
import weather

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def fuck_the_world_button(p1):
    w.TextBox.configure(text= "FUCK THE WORLD")

def hello_world_button(p1):
    w.TextBox.configure(text= "HELLO WORLD")
    w.TextBox.configure(text=weather.get_weather())

def get_weather(p1):
    w.TextBox.configure(text=weather.get_weather())

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()

