#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top60
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top60 {base} {
    if {$base == ""} {
        set base .top60
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m80" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x600+361+161
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1680 1005
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "FridgeBud"
    vTcl:DefineAlias "$top" "manage_settings" vTcl:Toplevel:WidgetProc "" 1
    button $top.but62 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Set Location 1} 
    vTcl:DefineAlias "$top.but62" "Location_1_set" vTcl:WidgetProc "manage_settings" 1
    button $top.cpd63 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Set Location 2} 
    vTcl:DefineAlias "$top.cpd63" "Location_2_set" vTcl:WidgetProc "manage_settings" 1
    button $top.cpd76 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Home 
    vTcl:DefineAlias "$top.cpd76" "home_button" vTcl:WidgetProc "manage_settings" 1
    menu $top.m80 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    button $top.cpd37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Quit Application} 
    vTcl:DefineAlias "$top.cpd37" "quit_button" vTcl:WidgetProc "manage_settings" 1
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Current Location 1} 
    vTcl:DefineAlias "$top.lab38" "current_work_label" vTcl:WidgetProc "manage_settings" 1
    label $top.cpd39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Current Location 2} 
    vTcl:DefineAlias "$top.cpd39" "current_weather_label" vTcl:WidgetProc "manage_settings" 1
    button $top.cpd38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Set Country} 
    vTcl:DefineAlias "$top.cpd38" "country_set" vTcl:WidgetProc "manage_settings" 1
    label $top.cpd40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Current Country} 
    vTcl:DefineAlias "$top.cpd40" "current_work_label1" vTcl:WidgetProc "manage_settings" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but62 \
        -in $top -x 80 -y 120 -width 167 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd63 \
        -in $top -x 80 -y 170 -width 167 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.cpd76 \
        -in $top -x 800 -y 530 -width 167 -height 32 -anchor nw \
        -bordermode inside 
    place $top.cpd37 \
        -in $top -x 620 -y 530 -width 167 -height 32 -anchor nw \
        -bordermode inside 
    place $top.lab38 \
        -in $top -x 270 -y 130 -width 701 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd39 \
        -in $top -x 270 -y 180 -width 701 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.cpd38 \
        -in $top -x 80 -y 70 -width 167 -height 42 -anchor nw \
        -bordermode inside 
    place $top.cpd40 \
        -in $top -x 270 -y 80 -width 701 -height 24 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top60

